---

version: "2"
services:

  jenkins:
    build:
      dockerfile: Dockerfile 
      context: jenkins
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      JENKINS_HOME: "/var/lib/jenkins"
    volumes: 
      - $PWD/jenkins_data:/var/lib/jenkins
    ports:
      - 8080:8080
    privileged: true


  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus
    volumes:
      - $PWD/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
