---

version: "3"
services:

  jenkins:
    build:
      dockerfile: Dockerfile 
      context: jenkins
    volumes: 
      - $PWD/jenkins_data:/var/jenkins_home
    ports:
      - 8080:8080


  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus
    volumes:
      - $PWD/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
