---

- name: CREATE SAMPLE JENKINS JOBS
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/all.yaml

  tasks:

  - jenkins_job:
      config: "{{ lookup('file', 'templates/job.xml.j2') }}"
      name: test job
      password: admin
      url: http://localhost:8080
      user: admin
    with_sequence: start=0 end=10 stride=2
